### ISSUE TITLE
Missing County Evaluation for USC-SIkJalpa

### ISSUE THREAD

**Issue by scc-usc** [youyanggu/covid19-forecast-hub-evaluation#3]
Hi,

I noticed in the following file that the evaluation for USC-SIkJalpha is missing
 /cases/summary/summary_4_weeks_ahead_counties.csv

I checked the corresponding submissions to make sure we didn't accidentally omit county-level forecast submission to reich lab, but they seem to be there. Could you please look into it?

Thanks,
Ajitesh

**Comment by youyanggu** [comment]
I think it's because you don't have "1 wk ahead inc case" targets for counties. Could you double check?

**Comment by scc-usc** [comment]
Yes, indeed a bug caused the dropping of some entries. Thanks for pointing this out. We will fix it in our next submissions.
